import { LIMITS as SHARED_LIMITS, MESSAGE_BYTE_LIMITS } from "../types/constants.js";

export const LIMITS = {
  STREAM_TTL_MS: 10 * 60 * 1000,
  ACTIVE_REPLY_TTL_MS: 60 * 60 * 1000,
  DEFAULT_DEBOUNCE_MS: 500,
  STREAM_MAX_BYTES: MESSAGE_BYTE_LIMITS.BOT_WS_STREAM,
  // 与 types/constants.ts 的 LIMITS 是同一个超时，别写成两个字面量。
  REQUEST_TIMEOUT_MS: SHARED_LIMITS.REQUEST_TIMEOUT_MS,
};
